# Generated by Django 5.1.1 on 2024-09-12 16:04

import employee.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Employee with this email already exists.'}, max_length=254, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='BD')),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='employee/photo')),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('hr', 'HR'), ('marketing', 'Marketing'), ('sales', 'Sales')], max_length=11)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(validators=[employee.validators.salary_validator])),
                ('date_of_leave', models.DateField(blank=True, help_text='Date at which employee leaved that company permanently', null=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Actual job responsibilities of that employee')),
            ],
        ),
    ]
