# Generated by Django 5.1.1 on 2024-09-14 18:05

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='employee/photo'),
        ),
    ]
